apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-frontend
  labels:
    name: hero-manager-frontend
spec:
  selector:
    matchLabels:
      name: hero-manager-frontend
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-frontend
    spec:
      containers:
        - name: hero-manager-frontend
          image: meicmcontainerregistry.azurecr.io/hero_manager_frontend_image:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: {}
