apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-scheduler
  labels:
    name: hero-manager-scheduler
spec:
  selector:
    matchLabels:
      name: hero-manager-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-scheduler
    spec:
      containers:
        - name: hero-manager-scheduler
          image: 904721383298.dkr.ecr.eu-west-2.amazonaws.com/meicm_ecr:hero_manager_scheduler_image_1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          resources: {}
          env:
            - name: PORT
              value: "8081"
            - name: MARVEL_SERVICE_URL
              value: "http://hero-manager-marvel:8082"
            - name: STATISTICS_SERVICE_URL
              value: "http://hero-manager-statistics:8083"
          envFrom:
            - configMapRef:
                name: hero-manager-database-configmap
